[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = [
  "dotnet restore",
  "dotnet build -c Release"
]

[phases.build]
cmds = [
  "dotnet publish -c Release -o ./publish"
]

[start]
cmd = "dotnet publish/DiyanetNamazVakti.Api.dll --urls http://0.0.0.0:$PORT"

